// SPDX-License-Identifier: MIT

import Forgejo from './forgejo.js';
import Gitea from './gitea.js';
import GitHub from './github.js';
import GitLab from './gitlab.js';

export const FORGES = {
    forgejo: Forgejo,
    gitea: Gitea,
    github: GitHub,
    gitlab: GitLab,
};

/**
 * Extract account and notification id
 * @param {String} id ID generated by Forge.formatID()
 * @returns {Array<String>}
 */
export function extractID(id) {
    const account = id.slice(0, 36);
    const notification = id.slice(37);

    return [account, notification];
}
